Add Redux   to React Components
ridabensalem/Bookstore- pull request #3
Opened 2023-03-07 12:40 UTC by ridabensalem

In this milestone of the Bookstore project we have added the following requirements : 
- Connect the store to the main component of  React app.
- Define a state slice that will contain the books.
- Display books.
- Add a <Button> component, which includes:
- [ ] An event handler that adds a book to the books array 
- Add a <Button> component, which includes:
- [ ] An event handler that removes a book from the books array 
- Add a <Button> component, which includes:
- [ ] - An event handler that checks the status

2023-03-07 13:42 UTC, youmari requested changes
Hi @ridabensalem , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-07 13:42 UTC, youmari commented on src/redux/Books/BooksSclice.js
>        state.list.push(action.payload);
- [ ] you're not exporting the  `bookSclice` as default so it returns an error when you run the app please make sure to fix that in order to review your app
<img width="908" alt="Screenshot 2023-03-07 at 14 39 37" src="https://user-images.githubusercontent.com/61790587/223439794-6a74d58b-d6e5-493a-bd95-648e3ddc0e1b.png">

2023-03-07 17:02 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @ridabensalem , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters

## Required Changes ♻️
 

- [ ] While you have made great progress, your app still can not be run, the are some dependencies issues, so I changed the eslint version but still has the same issue, please make sure you fix this issue.
<img width="726" alt="1" src="https://user-images.githubusercontent.com/77843050/223494749-d7b8c522-823d-474b-bf90-80348c75d2fc.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 09:06 UTC, zainsadaqat approved these changes
# Pull Request Approved ✅ 🎊 🎉 
## Hello @ridabensalem 👋 

## Things to Appreciate 
- [ ] Correct Flow ✅ 
- [ ] Clean Code 👍 
- [ ] No Linter Errors 🔥 
- [ ] Descriptive Pull Request and Summary 👌 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media4.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 09:24 UTC, merged